PorraGirona/Controllers/LoginController.cs
using PorraGirona.Models;
using PorraGirona.Models.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;

namespace PorraGironaWeb.Controllers
{
    public class LoginController : Controller
    {
        PostDbContext _context;
        public LoginController()
        {
            _context = new PostDbContext();
        }

        //Petició de la plana
        //La carregar el fitxer Startup.cs en pattern: "{controller=Login}/{action=Index}");

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        //Enviament de la plana (al polsar el botó enviar)
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                Penyiste penyista = null;
                //Consulta per veure si existeix el penyista a la base de dades amb les dades que ens han entrat al formulari
                try
                {
                    penyista = _context.Penyistes.FirstOrDefault(penyista => penyista.Alias.ToLower() == model.Alias.ToLower() && penyista.Password == model.Password);
                }
                catch (Exception) { }

                if (penyista != null)
                {
                    //Guardem el alias i rol en la sessió
                    HttpContext.Session.Set("alias", System.Text.Encoding.ASCII.GetBytes(penyista.Alias));
                    HttpContext.Session.Set("rol", System.Text.Encoding.ASCII.GetBytes(penyista.Rol));
                    HttpContext.Session.Set("idpenyista", System.Text.Encoding.ASCII.GetBytes(penyista.Idpenyista.ToString()));

                    //Then redirect to the Index Action method of Controller Puntuacions
                    return RedirectToAction("Index", "Puntuacions");
                }
                else
                {
                    ModelState.AddModelError("", "Usuari o password erroni");
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Logout()
        {
            HttpContext.Session.Remove("alias");
            HttpContext.Session.Remove("rol");
            HttpContext.Session.Remove("idpenyista");
            return RedirectToAction("Index");
        }
    }
}

PorraGirona/Controllers/PartitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PorraGirona.Models.Entity;

namespace PorraGirona.Controllers
{
    public class PartitsController : Controller
    {
        //private readonly PostDbContext _context;

        //public PartitsController(PostDbContext context)
        //{
        //    _context = context;
        //}
        PostDbContext _context;
        public PartitsController()
        {
            _context = new PostDbContext();
        }
        //Nivell Accés
        private int NivellAcces()
        {
            int nivell = 10;

            String rol;
            byte[] valor = null;
            bool existeix = HttpContext.Session.TryGetValue("rol", out valor);
            if (valor != null)
            {
                rol = System.Text.Encoding.UTF8.GetString(valor);
                if (rol == "admin")
                    nivell = 0;
                if (rol == "soci")
                    nivell = 5;
            }
            return nivell;
        }

        // GET: Partits
        public async Task<IActionResult> Index()
        {
            if (NivellAcces() != 0) // return RedirectToAction("Index","Login");
                return NotFound();
            else
            {
                //var postDbContext = _context.Partits.Include(p => p.IdequiplocalNavigation).Include(p => p.IdequipvisitantNavigation);
                //return View(await postDbContext.ToListAsync());
                return View(await _context.Partits.OrderBy(p => p.Jornada).ToListAsync());
            }

        }

        // GET: Partits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                var partit = await _context.Partits
                .Include(p => p.IdequiplocalNavigation)
                .Include(p => p.IdequipvisitantNavigation)
                .FirstOrDefaultAsync(m => m.Idpartit == id);
                if (partit == null)
                {
                    return NotFound();
                }

                return View(partit);
            }
        }

        // GET: Partits/Create
        public IActionResult Create()
        {
            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                ViewData["Idequiplocal"] = new SelectList(_context.Equips, "Idequip", "Idequip");
                ViewData["Idequipvisitant"] = new SelectList(_context.Equips, "Idequip", "Idequip");
                return View();
            }
        }

        // POST: Partits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idpartit,Idequiplocal,Idequipvisitant,Datainici,Jornada,Golslocal,Golsvisitant,Finalitzat,Temporada,Idsjugadorslocal,Idsjugadorsvisitant")] Partit partit)
        {
            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                if (ModelState.IsValid)
                {
                    _context.Add(partit);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["Idequiplocal"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequiplocal);
                ViewData["Idequipvisitant"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequipvisitant);
                return View(partit);
            }
        }

        // GET: Partits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                var partit = await _context.Partits.FindAsync(id);
                if (partit == null)
                {
                    return NotFound();
                }
                ViewData["Idequiplocal"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequiplocal);
                ViewData["Idequipvisitant"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequipvisitant);
                return View(partit);
            }
        }

        // POST: Partits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idpartit,Idequiplocal,Idequipvisitant,Datainici,Jornada,Golslocal,Golsvisitant,Finalitzat,Temporada,Idsjugadorslocal,Idsjugadorsvisitant")] Partit partit)
        {
            if (id != partit.Idpartit)
            {
                return NotFound();
            }

            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
                // return NotFound();
            else
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(partit);
                        await _context.SaveChangesAsync();

                        // Calcular puntuacions
                        List<Porre> porres = _context.Porres.FromSqlRaw("SELECT * FROM porres WHERE idpartit = " + partit.Idpartit).ToList();

                        foreach (Porre porra in porres)
                        {
                            List<Puntuacion> puntuacions = _context.Puntuacions.FromSqlRaw("SELECT * FROM puntuacions WHERE idpenyista = " + porra.Idpenyista).ToList();
                            puntuacions.First().Puntuacio += CalculaPuntuacioUtilitzantEntitatsAmbAlies(porra, partit);

                            _context.Puntuacions.Update(puntuacions.First());
                        }

                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PartitExists(partit.Idpartit))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }

                ViewData["Idequiplocal"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequiplocal);
                ViewData["Idequipvisitant"] = new SelectList(_context.Equips, "Idequip", "Idequip", partit.Idequipvisitant);
                return View(partit);
            }
        }

        // GET: Partits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                var partit = await _context.Partits
                .Include(p => p.IdequiplocalNavigation)
                .Include(p => p.IdequipvisitantNavigation)
                .FirstOrDefaultAsync(m => m.Idpartit == id);
                if (partit == null)
                {
                    return NotFound();
                }

                return View(partit);
            }
        }

        // POST: Partits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (NivellAcces() != 0) return RedirectToAction("Index", "Login");
            else
            {
                var partit = await _context.Partits.FindAsync(id);
                _context.Partits.Remove(partit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        private bool PartitExists(int id)
        {
            return _context.Partits.Any(e => e.Idpartit == id);
        }
        
        public static int CalculaPuntuacioUtilitzantEntitatsAmbAlies(Porre porra, Partit partit)
        {
            int puntuacio, guanyador, prediccioGuanyador;

            bool empat = partit.Golsvisitant == partit.Golslocal;

            // 0 per equip local, 1 per visitant
            guanyador = partit.Golslocal > partit.Golsvisitant ? 0 : 1;
            prediccioGuanyador = porra.Golslocal > porra.Golsvisitant ? 0 : 1;


            if (porra.Golslocal == partit.Golslocal && porra.Golsvisitant == partit.Golsvisitant) puntuacio = 5;

            else if (porra.Golslocal == partit.Golslocal || porra.Golsvisitant == partit.Golsvisitant) puntuacio = 4;

            else if (empat && porra.Golslocal == porra.Golsvisitant) puntuacio = 3;
            
            else if (guanyador == prediccioGuanyador) puntuacio = 3;

            else if (Math.Abs((double)(porra.Golslocal - partit.Golslocal)) <= 1 && Math.Abs((double)(porra.Golsvisitant - partit.Golsvisitant)) <= 1) puntuacio = 2;

            else puntuacio = 1;

            return puntuacio;
        }
    }
}

PorraGirona/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PorraGironaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <style>

        /*
            https://www.resultados-futbol.com/segunda2022/grupo1/calendario
            https://www.resultados-futbol.com/segunda2022/grupo1/jugadores
            https://www.resultados-futbol.com/segunda2022/grupo1/equipos

            Paleta de colors
                vermell super fosc 118;13;30, 	#760D1E
                vermell fosc 202;15;44  		#CA0F2C
                vermell mig 207;31;48 		#CF1F30
                vermell clar 227;30;60		#E31E3C
                groc 249;213;37			#F9D525
            */
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .titoldata {
            font-size: 4vw;
            color: white;
        }

        .contenidor {
            display: flex;
            justify-content: space-between;
        }

        .capcalera {
            width: 100%;
            float: left;
            text-align: center;
            color: white;
            border: 2px solid yellow;
            border-radius: 5px;
            background-color: #CA0F2C;
            margin-bottom: 2px;
        }

        .titolpronostic {
            width: 100%;
            text-align: center;
            /*font-size: 1.2em;*/
            font-size: 5vw;
            color: white;
        }

        .left {
            background-color: #CF1F30;
            padding: 1%;
            float: left;
            width: 30%; /* The width is 20%, by default */
        }

        .main {
            background-color: #CA0F2C;
            padding: 5px;
            float: left;
            width: 40%; /* The width is 60%, by default */
        }

        .right {
            background-color: #CF1F30;
            padding: 1%;
            float: left;
            width: 30%; /* The width is 20%, by default */
        }

        .pronosticlocal {
            width: 50%;
            float: left;
            background-color: #CA0F2C;
            text-align: center;
        }

        .pronosticvisitant {
            width: 50%;
            float: left;
            background-color: #CA0F2C;
            text-align: center;
        }

        .pronosticgols {
            text-align: center;
            font-size: 11vw;
            padding: 0px 10px 0 10px;
            color: black;
        }

        .pronosticacabat {
            background-color: white;
            color: black;
        }

        .resultatlocal {
            width: 50%;
            float: left;
            background-color: #CA0F2C;
            text-align: center;
            padding: 1%;
        }

        .resultatvisitant {
            width: 50%;
            float: left;
            background-color: #CA0F2C;
            text-align: center;
            padding: 1%;
        }

        .resultatgols {
            text-align: center;
            font-size: 3em;
        }

        .caixaenviar {
            text-align: center;
        }

        .botoenviar {
            background-color: #F9D525;
            text-align: center;
            font-size: 1.5em;
            margin-top: 10px;
            color: black;
        }

        .imatgebackground {
            background-image: url('escutsequips/Girona.jpg');
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
            margin: auto;
        }

        .caixaescut {
            background-color: #FFFFFF;
            text-align: center;
            padding: 1%;
            border-radius: 5px;
        }

        .imatgeresponsive {
            width: 75%;
            max-width: 150px;
            height: auto;
        }

        .imatgeajustada {
            object-fit: contain;
            text-align: center;
            padding: 1%;
            background-color: #CF1F30;
        }

        .barrahoritzontal {
            border: 2px solid #FFFFFF;
            border-radius: 5px;
            float: left;
            width: 100%;
            background-color: black;
        }

        .barraseparadora {
            border: 1px solid #FFFFFF;
            border-radius: 2px;
            float: left;
            width: 100%;
            margin-top: 5px;
        }

        .nomequip {
            text-align: center;
            font-size: 1.1em;
            color: white;
        }

        .titolgols {
            text-align: center;
            font-size: 1.4em;
            color: white;
        }

        .colortitol {
            color: #CA0F2C;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="color: #CA0F2C">
            <div class="container">
                <!-- Canviem al clicar al titol va al home -->
                <a class="navbar-brand" asp-controller="Puntuacions" asp-action="Index"> <font class="text-danger"> <b>Porra Girona</b></font></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">-->
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <!-- apartat de Login -->
                    <ul class="navbar-nav">
                        @if (HttpContextAccessor.HttpContext.Session.GetString("alias") != null)
                        {
                            <li class="nav-item">
                                <u><a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout:  <b>@HttpContextAccessor.HttpContext.Session.GetString("alias")</b></a></u>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                    <!-- Barra de menú -->
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            String rol = "";
                            byte[] rolsessio = null;
                            bool existeix = HttpContextAccessor.HttpContext.Session.TryGetValue("rol", out rolsessio);
                            if (existeix) rol = System.Text.Encoding.UTF8.GetString(rolsessio);
                            //Si és un usuari identificat amb sessió mostra els menús
                            if ((rol.Equals("soci")) || (rol.Equals("admin")))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Puntuacions" asp-action="Index">Puntuacions</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"> Privacitat</a>
                            </li>
                            if (rol.Equals("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Partits" asp-action="Index">Partits</a>
                                </li>
                            }

                        }
</div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>